### ISSUE TITLE
Make it work with Win OS

### ISSUE THREAD

**Issue by dereuromark** [cakephp/plugin-installer#11]
Currently the generated `plugins.php` config fiile on Win OS would be:

```php
<?php
return array (
  'plugins' => 
  array (
    'Tools' => 'E:\\PHP\\wamp\\www\\work\\sandbox3\\plugins\\Data\\vendor/dereuromark/cakephp-tools\\',
    'Geo' => 'E:\\PHP\\wamp\\www\\work\\sandbox3\\plugins\\Data\\vendor/dereuromark/cakephp-geo\\',
  ),
);
```

Ideally it should be relative, just as the declarations in the root composer.json file are:
```php
 'plugins' => 
  array (
    'Tools' => 'vendor/dereuromark/cakephp-tools\\',
    'Geo' => 'vendor/dereuromark/cakephp-geo\\',
```

Also note that the slashes should all be the same.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/plugin-installer/pull/6#issuecomment-70113428

**Comment by josegonzalez** [comment]
PR welcome ;)

**Comment by markstory** [comment]
I can take care of this.

**Comment by dereuromark** [comment]
I also think we shouldn't use var_export() either. It creates a strange CS, with spaces in `array (` and a 2 space indentation etc.

**Comment by markstory** [comment]
Rolling a custom PHP dumper seems a bit wasteful. Given that we can't use any dependencies it would be an entirely bespoke solution.
