### ISSUE TITLE
Composer installers

### ISSUE THREAD

**Issue by darxmac** [cakephp/plugin-installer#18]
If you have the composer installer package installed

```
"composer/installers": "~1.0",
```

it will override what plugin-installer does, and install plugins into /plugins and not vendors

**Comment by darxmac** [comment]
(i had another package that included it)

**Comment by ADmad** [comment]
Looks like the `CakePHPInstaller` class of `composer/installers` will have to be updated to ignore 3.x plugins.

**Comment by markstory** [comment]
@ADmad how would that work?

**Comment by ADmad** [comment]
@markstory No idea. That's what we need to figure out :P

**Comment by thomscode** [comment]
Was this issue ever resolved? I'm trying to write a custom installer for Drupal and am running into the same issue?
