### ISSUE TITLE
plugins.php - paths on windows

### ISSUE THREAD

**Issue by Krafcu** [cakephp/plugin-installer#20]
After instaling plugins through composer on windows host with vagrant shared folder i get:

```php
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'BootstrapUI' => 'D:/vagrant/code/ts/vendor/friendsofcake/bootstrap-ui/',
        'DebugKit' => 'D:/vagrant/code/ts/vendor/cakephp/debug_kit/',
        'Bake' => 'D:/vagrant/code/ts/vendor/cakephp/bake/',
        'Gourmet/Faker' => 'D:/vagrant/code/ts/vendor/gourmet/faker/',
        'Migrations' => 'D:/vagrant/code/ts/vendor/cakephp/migrations/',

    ]
];
```

If i use composer from guest linux box it's working fine with ```$baseDir``` instead of ```D:/vagrant/...```
Any way to go both ways? :]

**Comment by AD7six** [comment]
That should be fixed by #16, though it needs verifying.

**Comment by markstory** [comment]
@AD7six I merged all those related pull requests, and will tag a new plugin-installer tonight. I won't have time to test a VM install on windows though.

**Comment by Krafcu** [comment]
I can confirm that it works now. Although i had to change ```composer.json``` to follow up changes with ```post-autoload-dump``` and now the file is in ```vendor/cakephp-plugins.php```. Big thanks! :+1:

**Comment by AD7six** [comment]
Great news @Krafcu
