### ISSUE TITLE
Namespaces of custom plugins in /plugins incorrectly handled

### ISSUE THREAD

**Issue by nrother** [cakephp/plugin-installer#27]
I have a plugin that is normally installed via composer to /vendor, but I installed it by cloning the [git repo (of my fork)](https://github.com/nrother/cakephp3-bootstrap3-helpers) to /pluings because I work on it in parallel to my main app.

This plugin has a composer.json with 
```json
"autoload": {
		"psr-4": {
 			"Bootstrap3\\": "src"
		}
	},
```
But the plugin installer messes up the namespace in `cakephp-plugins.php` because it uses the folder name (which is `cakephp3-bootstrap3-helpers`) for plugins under /plugins, even if they have a correct composer.json (see. https://github.com/cakephp/plugin-installer/blob/master/src/Installer/PluginInstaller.php#L163)

I'm not completly sure if this is intentionally (as I could just rename the folder), but when this would work this would make the process of working on plugins in parallel a bit easier...

**Comment by jadb** [comment]
@nrother that's not the way you should be developing plugins - but if you do stick to it, just change the folder name.

**Comment by nrother** [comment]
Ok, is there a document showing the correct way of doing it? I always though that was the correct way...

**Comment by jadb** [comment]
Like any other PHP library, stand-alone with tests. Tests would guide development and confirm it works as expected by the app.

**Comment by markstory** [comment]
How to build a standalone plugin as part of an app isn't documented. Would it be useful to have as part of the plugin docs?

**Comment by AD7six** [comment]
You'd normally do this @nrother :+1: 

    git clone git@github.com:nrother/cakephp3-bootstrap3-helpers.git
    cd cakephp3-bootstrap3-helpers
    composer install
    phpunit
    etc.

Also, see [composer's docs](https://getcomposer.org/doc/05-repositories.md#vcs) regarding how you'd normally require a fork.

**Comment by nrother** [comment]
@markstory Yes, I think that would be useful. I often develop an application in several sub-projects to keeps things reusable.

**Comment by markstory** [comment]
@nrother Ok, I can add a section on how I do it at least.
