### ISSUE TITLE
Activating plugins via shell

### ISSUE THREAD

**Issue by bobmulder** [cakephp/plugin-installer#28]
Just a crazy idea; how would it be to activate / deactivate your plugin via the shell? 
I hate it to open up my `bootstrap.php` file to add one rule code...

Just an idea. I don't think this functionality fits in this plugin ;)

Greetz

**Comment by markstory** [comment]
The only wrinkle to that will be figuring out whether or not a plugin should have bootstrap/routes options set to true. Outside of that it sounds very doable.

**Comment by jadb** [comment]
@markstory - maybe by checking if it includes a bootstrap and/or routes file. Also offering an option to manually force the shell that adds the rule (not) to auto-load them even if they are (not) detected:

```
bin/cake activate DebugKit --with-bootstrap
bin/cake activate DebugKit --no-bootstrap
```

I don't mind manually adding plugin activation/deactivation to bootstrap (and personally prefer doing that instead of adding more code to be maintained), but just jotting what came to mind when I read that.

**Comment by bobmulder** [comment]
Via the shell you can set a true/false option so I was thinking about:

```
bin/cake plugin activate -b -r DebugKit // sets bootstrap-file (-b_ and routing (-r)
bin/cake plugin deactivate DebugKit

```

But the idea of @jadb is not bad too: lets check it automatically ;)

It's just an idea... Maybe I should add this feature in the [Utils plugin](http://github.com/cakemanager/cakephp-utils) or something ;)

**Comment by bobmulder** [comment]
@markstory What do you think? ;)

**Comment by markstory** [comment]
CLI flags could be a good solution.

**Comment by bobmulder** [comment]
Sorry for asking, but what do you exactly mean with CLI flags? I couldn't find it. You mean a shell?

**Comment by markstory** [comment]
I meant the -b & -r options you had in the previous example.

**Comment by bobmulder** [comment]
Ah okay I understand. If you want I can try to set up a shell, but testing shells is a little bit hard for me. Maybe you could give some help with tests...

**Comment by markstory** [comment]
There are some existing tests for the bake commands, they would be a good place to start.

**Comment by bobmulder** [comment]
Great idea. I Will make a start this evening

**Comment by bobmulder** [comment]
@markstory One question, what's the 'plugin name' when I work on this plugin? You are using the namespace `Cake` but my shell can't handle that as plugin...

**Comment by jadb** [comment]
@bobmulder you're working on the bake plugin, right?

**Comment by bobmulder** [comment]
@jadb No I try to work on this plugin. I want to add a shell and tasks, but I discovered this is not a real plugin, but more a library to work with composer ;) So the question is: How am I able to add a shell when the namespace is

**Comment by jadb** [comment]
Am not sure this package would be the right one. It probably should be part of core but I will let @markstory confirm that.

**Comment by markstory** [comment]
There exists a plugin task in CakePHP itself. That might be the best place to put something like this as it doesn't really feel like it belongs in bake to me.

**Comment by bobmulder** [comment]
@markstory But how should I contribute to that plugin? I thought we could add something like this to this plugin.

**Comment by markstory** [comment]
I don't think this plugin is a good fit as it doesn't provide any shell classes that CakePHP can use as it is primarily a composer extension. Either adding this functionality to Bake's PluginTask or creating a new core shell seem like reasonable options.

**Comment by bobmulder** [comment]
I think it's not clean to add this to the Bake plugin... It's completely focussed on baking stuff... Maybe I am allowed to add this feature to the [Utils plugin(http://github.com/cakemanager/cakephp-utils)? It's a collection of components, behaviors and shells, so it would fit. The only problem is that people have to load this plugin before being able to use the shell...

**Comment by bobmulder** [comment]
I have made a prototype at https://github.com/cakemanager/cakephp-utils/tree/develop-plugin-shell/src/Shell. Short example: 

```
// loading a plugin
bin/cake plugin load MyPlugin

// loading a plugin including bootstrap and routes
bin/cake plugin load -b -r MyPlugin

// unloading plugin
bin/cake plugin unload MyPlugin
```

**Comment by lorenzo** [comment]
That's pretty awesome @bobmulder

**Comment by bobmulder** [comment]
Thank you @lorenzo :). Hopefully got time soon to make some tests. And I got one bug already: I am only able to remove the current line of the `bootstrap.php` without its `\n`. That means that when you unload a plugin it will cause two empty lines in your `bootstap.php`

**Comment by AD7six** [comment]
@bobmulder Nice work =). Speaking for myself, I would welcome a PR adding what you've got, and consolidating with [the plugin-assets shell](https://github.com/cakephp/cakephp/blob/3.0/src/Shell/PluginAssetsShell.php).

**Comment by bobmulder** [comment]
@AD7six Thank you :). I will take a look at the plugin-assets shell. I don't know it yet ;) Like to hear if anybody got ideas or suggestions :)

**Comment by bobmulder** [comment]
Hey All, refering to @AD7six, I have read about the plugin-assets shell. What about implementing the loading / unloading feature in this shell? I am not familiair with contributing to such big applications, so maybe I could get some help...

**Comment by AD7six** [comment]
@bobmulder I think you are repeating what I meant. I am suggesting:

 * Move your plugin shell [here](https://github.com/cakephp/cakephp/tree/3.0/src/Shell)
 * Convert `PluginAssetShell` to a task
 * Include the aforementioned task in `PluginShell`
 * Create a pull request

Not forgetting to update [existing tests](https://github.com/cakephp/cakephp/blob/3.0/tests/TestCase/Shell/PluginAssetsShellTest.php) and add some for the added functionality of course.

i.e. enable this:

    bin/cake plugin load Foo
    bin/cake plugin unload Foo
    bin/cake plugin symlink Foo

**Comment by bobmulder** [comment]
@AD7six Thank you, that made it clear. Sorry for the question: on wich branch should I work?

**Comment by ADmad** [comment]
@bobmulder Create a new branch off 3.0 branch of core repo. Then once you are ready create a pull request for merging your branch into 3.0 of core repo.

**Comment by bobmulder** [comment]
@ADmad The core repo is a read-only repo with only the master branch. I guess it's just the cakephp repo?

**Comment by ADmad** [comment]
By core i meant [cakephp/cakephp](https://github.com/cakephp/cakephp), sorry for the confusion.

**Comment by bobmulder** [comment]
Maybe we should think about a way to load the plugin automatically after it has been loaded via composer? I am not sure if it would be the best, but there are cases where it should be nice...

**Comment by lorenzo** [comment]
closing as the related pull request was merged
