### ISSUE TITLE
`Undefined variable: baseDir` when installing some plugins

### ISSUE THREAD

**Issue by markstory** [cakephp/plugin-installer#30]
_From @elboletaire on April 26, 2016 17:31_

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.7
* Platform and Target: linux.

### What you did
The problem comes with one of my plugins, but can also be reproduced with plugins from `friendsofcake`. 

Steps to reproduce it with my plugin:

~~~bash
composer create-project cakephp/app testing
cd testing
composer require elboletaire/twbs-cake-plugin
~~~

If you wanna reproduce this with plugins from `friendsofcake` you need to install a few at once:

~~~bash
composer create-project cakephp/app testing
cd testing
composer require friendsofcake/crud friendsofcake/search friendsofcake/bootstrap-ui friendsofcake/crud-view
~~~

Please, note that installing `friendsofcake` plugins one by one will NOT throw the error!

### Expected Behavior
Generate the expected `cakephp-plugins.php` file instead of the one is currently generated (the problem is when it replaces the `$baseDir` variable)

### Actual Behavior
The `cakephp-plugins.php` file re-generated when running the steps above has an incorrect `$baseDir` definition. Here's the file generated after running the above steps:

~~~php
<?php
$baseDir = dirname(dirname($baseDir . '/vendor/cakephp/plugin-installer/src/Installer/PluginInstaller.php'));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',
        'BootstrapUI' => $baseDir . '/vendor/friendsofcake/bootstrap-ui/',
    ]
];
~~~

When it should be...

~~~php
<?php
$baseDir = dirname(dirname(__FILE__));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'DebugKit' => $baseDir . '/vendor/cakephp/debug_kit/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',
        'BootstrapUI' => $baseDir . '/vendor/friendsofcake/bootstrap-ui/',
    ]
];
~~~

I'm not sure about what's going on here, but seems to be a bug in the `cakephp/plugin-installer` module.

_Copied from original issue: cakephp/cakephp#8714_

**Comment by markstory** [comment]
Neat looks like the `__FILE__` reference inside the here doc was being replaced with the actual path when the file was included multiple times per run.

**Comment by elboletaire** [comment]
So, I understand that in the case of my plugin (which I'm installing alone) it's due to the `require`d packages on my `composer.json`.

I've just tried this on windows (using cygwin) and I cannot reproduce the issue here. Maybe this can help understand the problem.

**Comment by elboletaire** [comment]
If the problem is with the heredoc, why is not happening under windows? Sorry for my ignorance

**Comment by markstory** [comment]
I'm not sure. I was able to reproduce it a few times on OSX. Once I switched to a normal string I stopped seeing the issue.

**Comment by elboletaire** [comment]
Ok, let's leave it then as a "php-poltergeist" :expressionless: 

Thanks for the fast-fix Mark!

**Comment by markstory** [comment]
Merged and released in 0.0.13

**Comment by elboletaire** [comment]
Have you tried it? Doesn't seem to fix the `Undefined variable: $baseDir` issue :\

~~~bash
composer create-project cakephp/app testing
cd testing
composer require elboletaire/twbs-cake-plugin
~~~

~~~bash
composer create-project cakephp/app testing
cd testing
composer require friendsofcake/crud friendsofcake/search friendsofcake/bootstrap-ui friendsofcake/crud-view
~~~

Obviously I've ensured that the plugin-installer version used now is 0.0.13.

**Comment by mhagenbruch** [comment]
Does not work for me too an OSX

**Comment by markstory** [comment]
@elboletaire It did work when I was testing locally. I'll give it another shot today.

**Comment by markstory** [comment]
I missed some templates in #31. I've removed the duplication and fixed the remaining template to not let constants to be interpolated.

**Comment by elboletaire** [comment]
Thanks Mark. Do we also need a version upgrade? I guess that installing `cakephp/app` now will install version 0.0.13 which doesn't have this commit.

**Comment by markstory** [comment]
I'll make another tag with this fix.

**Comment by markstory** [comment]
0.0.14 tagged.

**Comment by markstory** [comment]
This [section of composer](https://github.com/composer/composer/blob/master/src/Composer/Plugin/PluginManager.php#L180-L196) might be the source of our woes, and why the `__FILE__` constant was automagically being replaced for us. I'll open an issue with composer/composer and see what they can come up with.

**Comment by elboletaire** [comment]
That makes sense. 

BTW I've checked if it works now and it does.

Thanks Mark! :smiley:

**Comment by markstory** [comment]
Sweet. Thanks for the help on this @elboletaire

**Comment by klvs** [comment]
Experiencing this on Ubuntu 14.04 via a shared vagrant directory. Host OS is OSX.

**Comment by markstory** [comment]
@klvs Have you updated to the latest composer & plugin-installer?

**Comment by klvs** [comment]
@markstory Yes, I'm using 0.0.15. Everything installs fine with composer but when I start the dev server with:

````bash
sudo /vagrant/project_name/bin/cake server -p 80 -H 0.0.0.0
````

I get:
```bash
Notice Error: Undefined variable: baseDir in [/vagrant/project_name/vendor/cakephp-plugins.php, line 2]

Exception: Plugin DebugKit could not be found. in [/vagrant/project_name/vendor/cakephp/cakephp/src/Core/Plugin.php, line 148]
```

**Comment by markstory** [comment]
@klvs What does your generated `vendor/cakephp-plugins.php` file look like?

**Comment by klvs** [comment]
@markstory 
vendor/cakephp-plugins.php
```php
<?php
$baseDir = dirname(dirname($baseDir . '/vendor/cakephp/plugin-installer/src/Installer/PluginInstaller.php'));
return [
    'plugins' => [
        'Bake' => $baseDir . '/vendor/cakephp/bake/',
        'BootstrapUI' => $baseDir . '/vendor/friendsofcake/bootstrap-ui/',
        'Migrations' => $baseDir . '/vendor/cakephp/migrations/',

    ]
];
```

Thank you for following up.

**Comment by elboletaire** [comment]
Can you also paste the output of `composer info`?

**Comment by klvs** [comment]
@elboletaire here you go
```bash
aura/installer-default                1.0.0   Installs Aura packages using the Composer defaults.
aura/intl                             1.1.1   The Aura.Intl package provides internationalization (I18N) tools, specifically
cakephp/bake                          1.2.3   Bake plugin for CakePHP 3.0
cakephp/cakephp                       3.2.8   The CakePHP framework
cakephp/chronos                       0.4.9   A simple API extension for DateTime.
cakephp/debug_kit                     3.2.7   CakePHP Debug Kit
cakephp/migrations                    1.5.7   Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer              0.0.15  A composer installer for CakePHP 3.0+ plugins.
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/instantiator                 1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
friendsofcake/bootstrap-ui            v0.4.1  Twitter Bootstrap 3 support for CakePHP 3
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jdorn/sql-formatter                   v1.2.17 a PHP SQL highlighting library
mobiledetect/mobiledetectlib          2.8.22  Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combined with specific HTTP headers to detect the mobile environment.
myclabs/deep-copy                     1.5.0   Create deep copies (clones) of your objects
nikic/php-parser                      v2.0.1  A PHP parser written in PHP
phpdocumentor/reflection-docblock     2.0.4
phpspec/prophecy                      v1.6.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             3.3.1   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.1   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.7   Utility class for timing
phpunit/php-token-stream              1.4.8   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.3.2   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.1.3   Mock Object library for PHPUnit
psr/log                               1.0.0   Common interface for logging libraries
psy/psysh                             v0.7.2  An interactive shell for modern PHP.
robmorgan/phinx                       v0.5.1  Phinx makes it ridiculously easy to manage the database migrations for your PHP app.
sebastian/code-unit-reverse-lookup    1.0.0   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.0   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1   Diff implementation
sebastian/environment                 1.3.5   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.1   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           1.0.0   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           1.0.2   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.0   Library that helps with managing the version number of Git-hosted PHP projects
symfony/config                        v3.0.4  Symfony Config Component
symfony/console                       v3.0.4  Symfony Console Component
symfony/filesystem                    v3.0.4  Symfony Filesystem Component
symfony/polyfill-mbstring             v1.1.1  Symfony polyfill for the Mbstring extension
symfony/var-dumper                    v3.0.4  Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.0.4  Symfony Yaml Component
twbs/bootstrap                        v3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
````

**Comment by klvs** [comment]
The issue seems to most composer install/update commands fail. Even for instance:
```bash
composer require cakephp/plugin-installer:0.0.15
````
With the same baseDir undefined error. I can't tell if it's failing after install cake debug kit or before. Maybe someone more experience can comment on the output of the above command?

```bash
Cannot create cache directory /home/vagrant/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/vagrant/.composer/cache/files/, or directory is not writable. Proceeding without cache
./composer.json has been updated
Cannot create cache directory /home/vagrant/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/vagrant/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing cakephp/debug_kit (3.2.7)
  - Installing cakephp/debug_kit (3.2.8)
    Downloading: 100%


Installation failed, reverting ./composer.json to its original content.


  [ErrorException]
  Undefined variable: baseDir
````

Notably, this doesn't seem to fail on a could ubuntu instance. Though the same one fails in vagrant? Perhaps this is a vagrant & osx issue? Seem unlikely but it's possible. I destroyed and reinstalled everything on a new vagrant instance just incase. 

Is there anywhere I can pitch in here? I could work off a server, but I'm dying to fix it now. I could be over looking something. I'll test more extensively if you don't think this is an issue with plugin-installer.

**Comment by ADmad** [comment]
@klvs Try removing plugin-installer, delete vendor/cakephp-plugins.php, reinstall plugin-installer again.

**Comment by klvs** [comment]
@ADmad That really helped.

It seems to be an issue upgrading from 0.0.12 to 0.0.15. This is what fixed it:

```bash
rm vendor/cakephp-plugins.php
composer remove cakephp/plugin-installer
composer remove cakephp/debug_kit
composer require cakephp/plugin-installer:0.0.15
composer require cakephp/debug_kit
```

...and back in business. I'll take a deeper look unless anyone has ideas? Thanks for the help.

**Comment by ADmad** [comment]
The installer code has been fixed but once the `cakephp-plugins.php` is borked, i think deleting it is the only way to fix it.

**Comment by klvs** [comment]
I'm not sure, I just compared my old one to the new one and there doesn't seem to be a [difference](https://www.diffchecker.com/ud9efg5x). My composer.json and composer.lock are in git and are reporting differences though. Will report on it soon.

**Comment by ADmad** [comment]
Btw instead of `composer require cakephp/plugin-installer:0.0.15` you should use `composer require cakephp/plugin-installer:^0.0.15` so that you get future updates.
