### ISSUE TITLE
Failed to extract with plugin installer and composer v2

### ISSUE THREAD

**Issue by dereuromark** [cakephp/plugin-installer#49]
https://travis-ci.com/github/dereuromark/cakephp-queue/jobs/407012609

composer 2.0.2

> 0/26 [>---------------------------]   0%    Failed to extract wyrihaximus/twig-view: (9) unzip -qq  '/home/travis/build/dereuromark/cakephp-queue/vendor/composer/tmp-0f44b557f583e04f542626ee3e611561' -d '/home/travis/build/dereuromark/cakephp-queue/vendor/composer/38d59301'
unzip:  cannot find or open /home/travis/build/dereuromark/cakephp-queue/vendor/composer/tmp-0f44b557f583e04f542626ee3e611561.
    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix

It looks like the plugin installer doesn't handle the downloaded files in a way, that they can be extracted.
Does anyone have has this issue?
It seems to affect most of my plugins.

**Comment by dereuromark** [comment]
Manually restricting the library to 1.3+ seems to solve it
https://github.com/dereuromark/cakephp-queue/commit/7abaac716b70f2e8a2b4f7695db4dc4c6ca0665b
But is there another way that doesn't require the manual addition maybe?

**Comment by ADmad** [comment]
Without a lock file I would expect the latest plugin installer version to be used. Your travis config [caches](https://github.com/dereuromark/cakephp-queue/blob/master/.travis.yml#L63) composer packages. So that might be the reason by the particular build used older version of the plugin installer.

**Comment by dereuromark** [comment]
It was prefer lowest going too far back. 1.0.0

**Comment by ADmad** [comment]
Okay. So if using `prefer-lowest` you will have to clamp the plugin installer to `1.3` since lower versions wont work with composer v2.

I don't think there's anything we can do here.

**Comment by dereuromark** [comment]
Yeah, probably nothing that makes the previous versions not installable here out of the box.
Well, all right, guess I have some travis fixing to do :/
