### ISSUE TITLE
Can't install plugins on Composer 2 and PHP < 7.2

### ISSUE THREAD

**Issue by nojimage** [cakephp/plugin-installer#50]
I am developing an application that can run on PHP 5.6.
After upgrading to Composer 2, I tried to update the plugin installer, but I couldn't update the installer due to the limitation of php >= 7.2.

Are you planning to release a 1.2.x version that supports Composer 2 ?

**Comment by nojimage** [comment]
Now, I backported 1.3 to 1.2. https://github.com/nojimage/plugin-installer/tree/composer-2
If you have a branch like `1.2.x`, I would like to send a PR.

**Comment by dereuromark** [comment]
Hm, maybe the installer should have gotten a major bump instead
v1 vs v2
I wonder if we can patch 1.2.x here as usually, inside semver, you would go to latest minor, and nothing blocks you from it in this case.
You would have to set the constraint from ^ to ~: `~1.2.x` etc manually.
