### ISSUE TITLE
Plugin could not be found after Upgrade to Plugin Installer 1.3.x with Composer 1.x & CakePHP 3.x

### ISSUE THREAD

**Issue by ravage84** [cakephp/plugin-installer#53]
CakePHP: 3.9.3
Composer:  1.10.17
OS: Windows & Linux
CakePHP Plugin Installer: 1.2.0 vs. 1.3.1

We recently updated the ``cakephp/plugin-installer`` dependency of a CakePHP 3.9.x application from ``1.2.0`` to ``1.3.1``.
Today we wanted to deploy that application but it failed with:

````
Fatal error: [Cake\Core\Exception\MissingPluginException] Plugin PluginToLoad could not be found. (/path/to/appvendor\cakephp\cakephp\src\Core\PluginCollection.php:207)
#0 /path/to/appvendor\cakephp\cakephp\src\Core\Plugin.php(254): Cake\Core\PluginCollection->get('PluginToLoad')
#1 /path/to/appvendor\cakephp\cakephp\src\Core\App.php(189): Cake\Core\Plugin::classPath('PluginToLoad'
 #2 /path/to/appvendor\cakephp\cakephp\src\View\View.php(1786): Cake\Core\App::path('Template', 'PluginToLoad')
#3 /path/to/appvendor\cakephp\cakephp\src\View\View.php(1600): Cake\View\View->_paths(NULL)
#4 /path/to/appvendor\cakephp\cakephp\src\View\View.php(888): Cake\View\View->_getViewFileName('Error\\error500')
#5 /path/to/appvendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(410): Cake\View\View->render('error500', 'error')
#6 /path/to/appvendor\cakephp\cake in /path/to/appvendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 181
````

After downgrading again to ``1.2.0``, it functioned again.

//cc @orca-services

**Comment by dereuromark** [comment]
You can use composer v2 and Cake3, I have apps that work this way
Is there a need for you to still use v1?

That said: I agree we should fix it though :) As there is no technical limit right now preventing anyone from downloading a new minor.

**Comment by ravage84** [comment]
> Is there a need for you to still use v1?

We simply haven't validated Composer compatibility in all cases. Once validated, we upgrade to Composer 2.

**Comment by othercorey** [comment]
Is the cakephp-plugins.php file generated correctly? Is there any plugin-installer output when running composer?

**Comment by ravage84** [comment]
@othercorey 
> Is the cakephp-plugins.php file generated correctly?

With a simple ``composer install`` and ``composer update`` it does.

> Is there any plugin-installer output when running composer?

No, I see no output. I had one before I deleted the hook I was instructed to delete.

But I found the difference:

For our build artifact, we use ``composer install --no-dev --optimize-autoloader --ignore-platform-reqs --prefer-dist --no-scripts ``. Aparently, the ``--no-scripts`` part is necessary for creating the ``cakephp-plugins.php``.

**Comment by ravage84** [comment]
@othercorey 
> Is the cakephp-plugins.php file generated correctly?

With a simple ``composer install`` and ``composer update`` it does.

> Is there any plugin-installer output when running composer?

No, I see no output. I had one before I deleted the hook I was instructed to delete.

But I found the difference:

For our build artifact, we use ``composer install --no-dev --optimize-autoloader --ignore-platform-reqs --prefer-dist --no-scripts ``. Aparently, the ``--no-scripts`` part is necessary for creating the ``cakephp-plugins.php``.

**Comment by ravage84** [comment]
At first, I thought we could run without ``--no-script`` but we want to make sure that when creating the build artifact, we must not run the ``Installer::postInstall`` script.

**Comment by dereuromark** [comment]
Then you just need to invoke the needed hook/script manually after composer install is finished.

**Comment by ravage84** [comment]
@dereuromark fine.

But if you mean the method ``\Cake\Composer\Installer\PluginInstaller::postAutoloadDump()``, it won't work as this class is deprecated and [the metthod does nothing (anymore)](https://github.com/cakephp/plugin-installer/blob/1.3.1/src/Installer/PluginInstaller.php#L46-L76).

The other one, ``Cake\Composer\Plugin::postAutoloadDump`` isn't static, so it can't be invoked.

Is there another way, I have overlooked?

**Comment by ADmad** [comment]
`composer dumpautoload --optimize` will generate the `cakephp-plugins.php` file.

**Comment by dereuromark** [comment]
Maybe we should update the README and adjust this snippet into it - for future references.

**Comment by ravage84** [comment]
@dereuromark yes, please.

**Comment by othercorey** [comment]
I wonder if `--no-scripts` works the same with composer v2.

**Comment by ADmad** [comment]
`--no-scripts` wouldn't run the autoload dump script in composer 1.x either.

**Comment by ravage84** [comment]
> `composer dumpautoload --optimize` will generate the `cakephp-plugins.php` file.

Here, again,  `composer dumpautoload --optimize`  must not be executed with `--no-scripts`. Because it will not generate the `cakephp-plugins.php`file, then.

But it seems the ``dumpautoload `` command does not invoke the same scripts (``post-install-cmd``) as ``composer install`` or ``composer update`` do. So it is OK.
