### ISSUE TITLE
  The CakePHP plugin installer v1.3+ no longer requires the  "post-autoload-dump" hook

### ISSUE THREAD

**Issue by cakejob** [cakephp/plugin-installer#59]
Cake\Composer\Installer\PluginInstaller::postAutoloadDump

                                                                                
     Action required!                                                           
                                                                                
     The CakePHP plugin installer v1.3+ no longer requires the                  
     "post-autoload-dump" hook. Please update your app's composer.json          
     file and remove usage of                                                   
     Cake\Composer\Installer\PluginInstaller::postAutoloadDump

**Comment by othercorey** [comment]
You did not explain the problem.

**Comment by dereuromark** [comment]
And the error message in details explains the solution and what to do.
