### ISSUE TITLE
0.0.2 causing issues

### ISSUE THREAD

**Issue by jadb** [cakephp/plugin-installer#8]
In most plugins, `cakephp/plugin-installer` is required as suggested in it's `README.md` file, using `*` which installs the latest **tagged** release. The fix has not been tagged and so one needs to use `dev-master` to work around that.

I think someone needs to update the instructions or push a new tag?

**Comment by davidyell** [comment]
I've updated to `0.0.2` and now I get this when I try to `composer update`.

```
PHP Fatal error:  Class 'Cake\Core\Configure\Engine\PhpConfig' not found
```

**Comment by dakota** [comment]
0.0.3 has been tagged with the fix for this problem
